export const REFERENCE_CONFIG: any = {
  agama: { title: "Agama", endpoint: "agama", columns: ["agama"] },
  ref_bank: { title: "Bank", endpoint: "ref_bank", columns: ["bank_name", "bank_code"] },
  ref_eselon: { title: "Eselon", endpoint: "ref_eselon", columns: ["eselon_name"] },
  ref_diklat: { title: "Jenis Diklat", endpoint: "ref_diklat", columns: ["diklat_name"] },
  ref_golongan: { title: "Golongan", endpoint: "ref_golongan", columns: ["golongan", "pangkat"] },
  ref_kawin: { title: "Status Kawin", endpoint: "ref_kawin", columns: ["status_kawin"] },
  unit: { title: "Unit Kerja", endpoint: "unit", columns: ["unit_kerja"] },
  ref_kota: { title: "Kota/Kabupaten", endpoint: "ref_kota", columns: ["kota_name"] },
  ref_kedudukan: { title: "Kedudukan Pegawai", endpoint: "ref_kedudukan", columns: ["kedudukan_name"] },
  ref_pegawai_jenis: { title: "Jenis Pegawai", endpoint: "ref_pegawai_jenis", columns: ["jenis_pegawai"] },
  ref_pejabat_ttd: { title: "Pejabat TTD", endpoint: "ref_pejabat_ttd", columns: ["pejabat_name"] },
  ref_pekerjaan: { title: "Pekerjaan", endpoint: "ref_pekerjaan", columns: ["pekerjaan_name"] },
  ref_pendidikan: { title: "Tingkat Pendidikan", endpoint: "ref_pendidikan", columns: ["tingkat_pendidikan"] },
  ref_provinsi: { title: "Provinsi", endpoint: "ref_provinsi", columns: ["provinsi_name"] },
  ref_status_keluarga: { title: "Status Keluarga", endpoint: "ref_status_keluarga", columns: ["status_keluarga"] },
  status_kehadiran: { title: "Status Kehadiran", endpoint: "status_kehadiran", columns: ["status_kehadiran"] },
  ref_sumber_gaji: { title: "Sumber Gaji", endpoint: "ref_sumber_gaji", columns: ["sumber_gaji"] },
  ref_tandajasa: { title: "Tanda Jasa", endpoint: "ref_tandajasa", columns: ["tandajasa_name"] },
  ref_usia: { title: "Kategori Usia", endpoint: "ref_usia", columns: ["usia_range"] },
  jabatan_fungsional: { title: "Jabatan Fungsional", endpoint: "jabatan_fungsional", columns: ["jabatan_fungsional_name"] },
  jabatan_grup: { title: "Grup Jabatan", endpoint: "jabatan_grup", columns: ["grup_name"] },
  jabatan_jenis: { title: "Jenis Jabatan", endpoint: "jabatan_jenis", columns: ["jenis_name"] },
  jabatan: { title: "Jabatan", endpoint: "jabatan", columns: ["jabatan_name"] },
};
